name: Daily Commit

on:
  schedule:
    - cron: '0 12 * * *'  # This runs every day at 12:00 PM UTC

jobs:
  daily_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create a commit
        run: |
          echo "Daily commit from GitHub Action" >> daily_commit.txt
          git config --local user.email "kavipriya.manivannan@straive.com"
          git config --local user.name "GitHub Action"
          git add daily_commit.txt
          git commit -m "Daily commit from GitHub Action" || echo "No changes to commit"
      
      - name: Push changes
        run: git push
